ALTER TABLE public."StripeWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LicenseKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PolarWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vulnerability_telemetry ENABLE ROW LEVEL SECURITY;
